# Generated by Django 5.1.2 on 2024-12-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_type', models.CharField(choices=[('Essay', 'Essay'), ('Lab Report', 'Lab Report'), ('Presentation', 'Presentation')], max_length=50)),
                ('uploaded_assignment', models.FileField(upload_to='assignments/')),
                ('uploaded_rubric', models.FileField(upload_to='rubrics/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
