# Generated by Django 5.1.2 on 2024-12-28 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_assignment_delete_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('Essay', 'Essay'), ('Lab Report', 'Lab Report'), ('Presentation', 'Presentation'), ('Narrative', 'Narrative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.CharField(default='for fun', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_rubric',
            field=models.FileField(blank=True, null=True, upload_to='rubrics/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.assignment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
