# Generated by Django 5.1.2 on 2024-12-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='uploaded_rubric',
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='final_percent',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rubric_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
