# Generated by Django 5.1.2 on 2025-01-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_assignment_text_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='text_content',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_assignment',
            field=models.FileField(default=None, upload_to='assignments/'),
            preserve_default=False,
        ),
    ]
